project_id = "ihfedqwzjldkpvfojeks"

[functions.get-booked-slots]
verify_jwt = false

[functions.admin-update-password]
verify_jwt = false

[functions.apply-specialty-block]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.send-cancellation-email]
verify_jwt = false

[functions.send-reminder-email]
verify_jwt = false

[functions.send-suspension-email]
verify_jwt = false

[functions.send-suspension-lifted-email]
verify_jwt = false

[functions.send-reschedule-email]
verify_jwt = false

[functions.send-feedback-email]
verify_jwt = false
